name: 'Docker Bump'
description: 'Trigger a GitHub workflow whenever a target image is out-of-date with its dependent base image'
inputs:
  target-image-name:
    description: 'Name of the image to check'
    required: true
  base-image-name:
    description: 'Name of the base image the target image is based on'
    default: ''
  dockerfile:
    description: 'Path to the Dockerfile used to build the target image'
    default: ''
  base-stage-name:
    description: 'Name of the stage in the Dockerfile associated with the base image'
    default: ''
  arch:
    description: 'Default architecture of the image'
    default: amd64
  repository:
    description: 'Name of GitHub repository containing the workflow to trigger'
    default: ${{ github.repository }}
  event-type:
    description: 'Name of the event that will be sent for the repository dispatch'
    default: 'base-image-update'
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT) used to send the repository dispatch'
    default: ${{ github.token }}
outputs:
  dispatch-sent:
    description: "A value indicating whether a repository dispatch was sent"
    value: ${{ steps.report-status.outputs.dispatch-sent }}
runs:
  using: "composite"
  steps:
    - name: Check Image
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $targetImage = "${{ inputs.target-image-name }}"
        $baseImage = "${{ inputs.base-image-name }}"
        $dockerfile = "${{ inputs.dockerfile }}"
        $baseStage = "${{ inputs.base-stage-name }}"
        $arch = "${{ inputs.arch }}"

        $dockerBumpCheckerVersion = "0.2.0"

        $containerName = "docker-bump-checker"
        $containerSrcPath = "/src"

        # The repo directory will be volume-mounted into the container so the Dockerfile path needs to be modified accordingly
        $dockerfile = "$containerSrcPath/$dockerfile"
        $result = docker run `
          --name $containerName `
          -v ${env:GITHUB_WORKSPACE}:$containerSrcPath `
          ghcr.io/mthalman/docker-bump-checker:$dockerBumpCheckerVersion `
          -BaseImage `"$baseImage`" `
          -TargetImage `"$targetImage`" `
          -DockerfilePath `"$dockerfile`" `
          -BaseStageName `"$baseStage`" `
          -Architecture `"$arch`"
        if ($LASTEXITCODE -ne 0) {
          throw "command failed"
        }

        docker cp ${containerName}:/home/app/log.txt log.txt
        if ($LASTEXITCODE -ne 0) {
          throw "command failed"
        }

        Get-Content log.txt
        docker rm $containerName
        if ($LASTEXITCODE -ne 0) {
          throw "command failed"
        }
        
        echo "TRIGGER_WORKFLOW=$result" >> "$env:GITHUB_ENV"
    - name: Repository Dispatch
      if: env.TRIGGER_WORKFLOW == 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ inputs.token }}
        repository: ${{ inputs.repository }}
        event-type: ${{ inputs.event-type }}
    - name: Report Status
      id: report-status
      shell: pwsh
      run: |
        if ($env:TRIGGER_WORKFLOW -eq "true") {
          echo "A repository dispatch was sent to '${{ inputs.repository }}' with event type '${{ inputs.event-type }}'."
        } else {
          echo "No repository dispatch was sent."
        }

        echo "dispatch-sent=$env:TRIGGER_WORKFLOW" >> "$env:GITHUB_OUTPUT"
