name: Docker Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mthalman/docker-bump-checker

defaults:
  run:
    working-directory: container

jobs:

  docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./container
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
